const Icon = ({ children, className = '' }) => <span className={`app-icon ${className}`}>{children}</span>;

export function HomeScreen() {
  return <div className="phone-screen adon-screen home-screen">
    <div className="status-line"><b>1:54</b><span>⌁ ◔ ▮▮▮ <em>75</em></span></div>
    <div className="home-banner"><div className="reward-tag">Local rewards</div><div className="banner-actions"><span>♧<i /></span><span>♙</span></div><h3>What's happening in Nagpur</h3><p>Events, rewards &amp; trending offers around you</p><div className="banner-pills"><b>●&nbsp; Nagpur⌄</b><b>₹&nbsp; Earn rewards</b></div></div>
    <div className="goal-card"><div className="goal-ring"><strong>0</strong><small>/5</small></div><div><b>Daily ad goal</b><p>Watch 5 more ads to hit<br/>your goal</p><div className="dots"><i/><i/><i/><i/><i/></div></div><div className="streak-sleep">Zz<small>No streak</small></div></div>
    <h3 className="browse-title">Browse Categories</h3><div className="app-categories"><div><Icon className="peach">♪</Icon><b>Live Concerts</b></div><div><Icon className="lavender">♜</Icon><b>Entertainment</b></div><div><Icon className="sky">◆</Icon><b>Workshops</b></div><div><Icon className="mint">◉</Icon><b>Sports</b></div></div><BottomTab active="Events" />
  </div>;
}

export function ReelsScreen() { return <div className="phone-screen reel-screen"><div className="coffee-photo"><div className="coffee-sign">FILTER COFFEE</div><div className="coffee-counter"/><div className="cup"><i/></div></div><div className="status-line reel-status"><b>1:54</b><span>⌁ ◔ ▮▮▮ <em>74</em></span></div><div className="reel-actions"><span>♡<b>1</b></span><span>◉<b>1</b></span><span>⌯<b>5</b></span><span>●<b>Map</b></span><span className="coin">$<b>₹0.25</b></span></div><div className="reel-copy"><div className="reel-user"><i>S</i><b>Sanchit Shahare</b></div><h3>Hii</h3><p>Hii</p></div><div className="reel-reward">💰 <b>₹0.00 today · 5 left</b>⌃</div><div className="reel-timer"><i/><b>29 sec left</b></div><BottomTab active="Ads" /></div>; }

export function ProfileScreen() { const items = [['♙','My Account','Update profile details','sky'],['▯','My Bookings','View saved tickets','peach'],['⌁','Create Ad','Promote to nearby audiences','mint'],['⊕','Create Event','Launch a new local event','lavender'],['⌁','My Ads','View and track ad performance','cyan'],['▣','My Events','Track and manage your shows','orange']]; return <div className="phone-screen adon-screen profile-screen"><div className="status-line"><b>1:54</b><span>⌁ ◔ ▮▮▮ <em>74</em></span></div><div className="profile-heading"><span>‹</span><h3>Profile</h3></div><div className="creator-banner"><Icon>♙</Icon><b>Creator dashboard</b><h3>Manage your account, events, ads, bookings, and earnings from one place.</h3><p>Your organizer tools are active and ready to use.</p></div><div className="profile-grid">{items.map(([icon,title,copy,color]) => <div className="profile-item" key={title}><Icon className={color}>{icon}</Icon><h4>{title}</h4><p>{copy}</p></div>)}</div></div>; }
export function WalletScreen() { return <HomeScreen />; } export function EventsScreen() { return <ProfileScreen />; } export function QRScreen() { return <HomeScreen />; }
function BottomTab({ active }) { return <div className="app-tabs"><div className={active === 'Events' ? 'selected' : ''}><span>▣</span>Events</div><div className={active === 'Ads' ? 'selected' : ''}><span>⊙</span>Ads</div></div>; }
